---
- name: Create project directory
  file:
    path: /opt/devops-lab
    state: directory

- name: Copy SQL Seed Data
  copy:
    src: init.sql
    dest: /opt/devops-lab/init.sql

- name: Copy Prometheus Config
  template:
    src: prometheus.yml.j2
    dest: /opt/devops-lab/prometheus.yml

- name: Copy Docker Compose File
  template:
    src: docker-compose.yml.j2
    dest: /opt/devops-lab/docker-compose.yml

- name: Deploy the Stack (Swarm)
  docker_stack:
    state: present
    name: prod
    compose:
      - /opt/devops-lab/docker-compose.yml